"""add processed idpks

Revision ID: 4f973b372ca6
Revises: d4f2a8c19b31
Create Date: 2026-09-20 16:01:13.173814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f973b372ca6'
down_revision: Union[str, Sequence[str], None] = 'd4f2a8c19b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_idpks',
    sa.Column('idpk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cycle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idpk')
    )
    op.create_index(op.f('ix_processed_idpks_cycle_id'), 'processed_idpks', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_processed_idpks_message_type'), 'processed_idpks', ['message_type'], unique=False)
    op.create_index(op.f('ix_processed_idpks_msg_id'), 'processed_idpks', ['msg_id'], unique=False)
    op.create_index(op.f('ix_processed_idpks_processed_at'), 'processed_idpks', ['processed_at'], unique=False)

    #Conserva la idempotencia de operaciones aplicadas antes de introducir processed_idpks.
    op.execute(
        sa.text(
            """
            INSERT INTO processed_idpks (
                idpk,
                msg_id,
                message_type,
                cycle_id,
                processed_at
            )
            SELECT DISTINCT ON (idpk)
                idpk,
                msg_id,
                message_type,
                cycle_id,
                processed_at
            FROM inbound_messages
            WHERE status = 'PROCESSED'
              AND idpk IS NOT NULL
              AND msg_id IS NOT NULL
              AND message_type IS NOT NULL
              AND processed_at IS NOT NULL
            ORDER BY idpk, processed_at ASC
            ON CONFLICT (idpk) DO NOTHING
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_idpks_processed_at'), table_name='processed_idpks')
    op.drop_index(op.f('ix_processed_idpks_msg_id'), table_name='processed_idpks')
    op.drop_index(op.f('ix_processed_idpks_message_type'), table_name='processed_idpks')
    op.drop_index(op.f('ix_processed_idpks_cycle_id'), table_name='processed_idpks')
    op.drop_table('processed_idpks')
    # ### end Alembic commands ###
