"""add protocol errors

Revision ID: a021fb2813c1
Revises: e3146c521ba8
Create Date: 2026-09-16 21:03:29.138692

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a021fb2813c1'
down_revision: Union[str, Sequence[str], None] = 'e3146c521ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idpk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cycle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('target_msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('cap', sa.Float(), nullable=True),
    sa.Column('spare', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_errors_cycle_id'), 'protocol_errors', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_protocol_errors_idpk'), 'protocol_errors', ['idpk'], unique=False)
    op.create_index(op.f('ix_protocol_errors_msg_id'), 'protocol_errors', ['msg_id'], unique=True)
    op.create_index(op.f('ix_protocol_errors_reason'), 'protocol_errors', ['reason'], unique=False)
    op.create_index(op.f('ix_protocol_errors_received_at'), 'protocol_errors', ['received_at'], unique=False)
    op.create_index(op.f('ix_protocol_errors_target_msg_id'), 'protocol_errors', ['target_msg_id'], unique=False)
    op.create_index(op.f('ix_protocol_errors_timestamp'), 'protocol_errors', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_protocol_errors_timestamp'), table_name='protocol_errors')
    op.drop_index(op.f('ix_protocol_errors_target_msg_id'), table_name='protocol_errors')
    op.drop_index(op.f('ix_protocol_errors_received_at'), table_name='protocol_errors')
    op.drop_index(op.f('ix_protocol_errors_reason'), table_name='protocol_errors')
    op.drop_index(op.f('ix_protocol_errors_msg_id'), table_name='protocol_errors')
    op.drop_index(op.f('ix_protocol_errors_idpk'), table_name='protocol_errors')
    op.drop_index(op.f('ix_protocol_errors_cycle_id'), table_name='protocol_errors')
    op.drop_table('protocol_errors')
    # ### end Alembic commands ###
