"""message audit inbox outbox

Revision ID: a8f071ada8eb
Revises: e3146c521ba8
Create Date: 2026-09-16 14:36:55.697392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8f071ada8eb'
down_revision: Union[str, Sequence[str], None] = 'a021fb2813c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idpk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cycle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_messages_cycle_id'), 'inbound_messages', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_inbound_messages_idpk'), 'inbound_messages', ['idpk'], unique=False)
    op.create_index(op.f('ix_inbound_messages_message_type'), 'inbound_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_inbound_messages_msg_id'), 'inbound_messages', ['msg_id'], unique=False)
    op.create_index(op.f('ix_inbound_messages_reason_code'), 'inbound_messages', ['reason_code'], unique=False)
    op.create_index(op.f('ix_inbound_messages_received_at'), 'inbound_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_inbound_messages_status'), 'inbound_messages', ['status'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idpk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cycle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('routing_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msg_id', name='uq_outbound_message_msg_id')
    )
    op.create_index(op.f('ix_outbound_messages_created_at'), 'outbound_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbound_messages_cycle_id'), 'outbound_messages', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_idpk'), 'outbound_messages', ['idpk'], unique=False)
    op.create_index(op.f('ix_outbound_messages_message_type'), 'outbound_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_outbound_messages_msg_id'), 'outbound_messages', ['msg_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_status'), 'outbound_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_messages_target_msg_id'), 'outbound_messages', ['target_msg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_messages_target_msg_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_status'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_msg_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_message_type'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_idpk'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_cycle_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_created_at'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_inbound_messages_status'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_received_at'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_reason_code'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_msg_id'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_message_type'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_idpk'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_cycle_id'), table_name='inbound_messages')
    op.drop_table('inbound_messages')
    # ### end Alembic commands ###
