"""E1 ledger schema

Revision ID: e3146c521ba8
Revises: 48ac5d6a989a
Create Date: 2026-09-16 14:06:05.391453

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3146c521ba8'
down_revision: Union[str, Sequence[str], None] = '48ac5d6a989a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('cycle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_idpk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_capacity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('consumption', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('generation_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opening_budget_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('opening_energy_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('budget_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('energy_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('last_operation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_operation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_index(op.f('ix_cycles_status_idpk'), 'cycles', ['status_idpk'], unique=False)
    op.create_index(op.f('ix_cycles_status_msg_id'), 'cycles', ['status_msg_id'], unique=False)
    op.create_table('negotiation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idpk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('energy_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.cycle_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idpk'),
    sa.UniqueConstraint('msg_id')
    )
    op.create_index(op.f('ix_negotiation_reports_cycle_id'), 'negotiation_reports', ['cycle_id'], unique=True)
    op.create_table('negotiations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idpk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latest_msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('offered_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmed_energy', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('confirmed_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('payment_quantity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.cycle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiations_cycle_id'), 'negotiations', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_negotiations_idpk'), 'negotiations', ['idpk'], unique=True)
    op.create_index(op.f('ix_negotiations_status'), 'negotiations', ['status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('operation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idpk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_msg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('negotiation_id', sa.Integer(), nullable=True),
    sa.Column('budget_delta', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('energy_delta', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('budget_after', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('energy_after', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.cycle_id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'sequence_no', name='uq_ledger_cycle_sequence'),
    sa.UniqueConstraint('idpk', 'operation_type', name='uq_ledger_idempotent_effect')
    )
    op.create_index(op.f('ix_ledger_entries_cycle_id'), 'ledger_entries', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_idpk'), 'ledger_entries', ['idpk'], unique=False)
    op.create_index(op.f('ix_ledger_entries_operation_type'), 'ledger_entries', ['operation_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_source_msg_id'), 'ledger_entries', ['source_msg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_source_msg_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_operation_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_idpk'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_cycle_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_negotiations_status'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_idpk'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_cycle_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_negotiation_reports_cycle_id'), table_name='negotiation_reports')
    op.drop_table('negotiation_reports')
    op.drop_index(op.f('ix_cycles_status_msg_id'), table_name='cycles')
    op.drop_index(op.f('ix_cycles_status_idpk'), table_name='cycles')
    op.drop_table('cycles')
    # ### end Alembic commands ###
